<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $data = array(
            array('city_id' => '444','city_province_id' => '1','city_name' => 'اهر'),
            array('city_id' => '445','city_province_id' => '1','city_name' => 'هریس'),
            array('city_id' => '446','city_province_id' => '1','city_name' => 'بستان آباد'),
            array('city_id' => '447','city_province_id' => '1','city_name' => 'بناب'),
            array('city_id' => '448','city_province_id' => '1','city_name' => 'تبریز'),
            array('city_id' => '449','city_province_id' => '1','city_name' => 'آذرشهر'),
            array('city_id' => '450','city_province_id' => '1','city_name' => 'اسکو'),
            array('city_id' => '451','city_province_id' => '1','city_name' => 'سراب'),
            array('city_id' => '452','city_province_id' => '1','city_name' => 'شبستر'),
            array('city_id' => '453','city_province_id' => '1','city_name' => 'کلیبر'),
            array('city_id' => '456','city_province_id' => '1','city_name' => 'مراغه'),
            array('city_id' => '457','city_province_id' => '1','city_name' => 'عجب شیر'),
            array('city_id' => '458','city_province_id' => '1','city_name' => 'مرند'),
            array('city_id' => '459','city_province_id' => '1','city_name' => 'جلفا'),
            array('city_id' => '460','city_province_id' => '1','city_name' => 'ملکان'),
            array('city_id' => '461','city_province_id' => '1','city_name' => 'میانه'),
            array('city_id' => '462','city_province_id' => '1','city_name' => 'هشترود'),
            array('city_id' => '463','city_province_id' => '1','city_name' => 'چارااویماق'),
            array('city_id' => '464','city_province_id' => '1','city_name' => 'ورزقان'),
            array('city_id' => '465','city_province_id' => '2','city_name' => 'ارومیه'),
            array('city_id' => '466','city_province_id' => '2','city_name' => 'بوکان'),
            array('city_id' => '467','city_province_id' => '2','city_name' => 'پیرانشهر'),
            array('city_id' => '468','city_province_id' => '2','city_name' => 'سردشت'),
            array('city_id' => '469','city_province_id' => '2','city_name' => 'خوی'),
            array('city_id' => '471','city_province_id' => '2','city_name' => 'سلماس'),
            array('city_id' => '472','city_province_id' => '2','city_name' => 'ماکو'),
            array('city_id' => '473','city_province_id' => '2','city_name' => 'چالدران'),
            array('city_id' => '476','city_province_id' => '2','city_name' => 'مهاباد'),
            array('city_id' => '477','city_province_id' => '2','city_name' => 'میاندوآب'),
            array('city_id' => '478','city_province_id' => '2','city_name' => 'شاهین دژ'),
            array('city_id' => '479','city_province_id' => '2','city_name' => 'تکاپ'),
            array('city_id' => '480','city_province_id' => '2','city_name' => 'نقده'),
            array('city_id' => '481','city_province_id' => '2','city_name' => 'اشنویه'),
            array('city_id' => '482','city_province_id' => '3','city_name' => 'اردبیل'),
            array('city_id' => '483','city_province_id' => '3','city_name' => 'نمین'),
            array('city_id' => '484','city_province_id' => '3','city_name' => 'نیر'),
            array('city_id' => '485','city_province_id' => '3','city_name' => 'سرعین'),
            array('city_id' => '486','city_province_id' => '3','city_name' => 'پارس آباد'),
            array('city_id' => '487','city_province_id' => '3','city_name' => 'بیله سوار'),
            array('city_id' => '488','city_province_id' => '3','city_name' => 'خلخال'),
            array('city_id' => '489','city_province_id' => '3','city_name' => 'کوثر'),
            array('city_id' => '490','city_province_id' => '3','city_name' => 'گرمی'),
            array('city_id' => '491','city_province_id' => '3','city_name' => 'مشگین دشت'),
            array('city_id' => '492','city_province_id' => '4','city_name' => 'اردستان'),
            array('city_id' => '493','city_province_id' => '4','city_name' => 'شاهین شهر'),
            array('city_id' => '494','city_province_id' => '4','city_name' => 'میمه'),
            array('city_id' => '495','city_province_id' => '4','city_name' => 'بربخوار'),
            array('city_id' => '496','city_province_id' => '4','city_name' => 'خمینی شهر'),
            array('city_id' => '497','city_province_id' => '4','city_name' => 'سمیرم'),
            array('city_id' => '498','city_province_id' => '4','city_name' => 'شهرضا'),
            array('city_id' => '501','city_province_id' => '4','city_name' => 'فریدن'),
            array('city_id' => '502','city_province_id' => '4','city_name' => 'چادگان'),
            array('city_id' => '503','city_province_id' => '4','city_name' => 'فریدونشهر'),
            array('city_id' => '506','city_province_id' => '4','city_name' => 'فلاورجان'),
            array('city_id' => '507','city_province_id' => '4','city_name' => 'کاشان'),
            array('city_id' => '508','city_province_id' => '4','city_name' => 'آران و بیدگل'),
            array('city_id' => '509','city_province_id' => '4','city_name' => 'گلپایگان'),
            array('city_id' => '510','city_province_id' => '4','city_name' => 'خوانسار'),
            array('city_id' => '511','city_province_id' => '4','city_name' => 'لنجان'),
            array('city_id' => '512','city_province_id' => '4','city_name' => 'مبارکه'),
            array('city_id' => '513','city_province_id' => '4','city_name' => 'نائین'),
            array('city_id' => '516','city_province_id' => '4','city_name' => 'نجف آباد'),
            array('city_id' => '517','city_province_id' => '4','city_name' => 'تیران'),
            array('city_id' => '518','city_province_id' => '4','city_name' => 'کرون'),
            array('city_id' => '519','city_province_id' => '4','city_name' => 'نطنز'),
            array('city_id' => '521','city_province_id' => '5','city_name' => 'ساوجبلاغ'),
            array('city_id' => '522','city_province_id' => '5','city_name' => 'نظر آباد'),
            array('city_id' => '523','city_province_id' => '5','city_name' => 'طالقان'),
            array('city_id' => '524','city_province_id' => '5','city_name' => 'کرج'),
            array('city_id' => '525','city_province_id' => '5','city_name' => 'اشتهارد'),
            array('city_id' => '526','city_province_id' => '5','city_name' => 'فردیس'),
            array('city_id' => '527','city_province_id' => '6','city_name' => 'ایلام'),
            array('city_id' => '528','city_province_id' => '6','city_name' => 'ایوان'),
            array('city_id' => '529','city_province_id' => '6','city_name' => 'چرداول'),
            array('city_id' => '530','city_province_id' => '6','city_name' => 'مهران'),
            array('city_id' => '532','city_province_id' => '6','city_name' => 'شیروان'),
            array('city_id' => '533','city_province_id' => '6','city_name' => 'دهلران'),
            array('city_id' => '534','city_province_id' => '6','city_name' => 'دره شهر'),
            array('city_id' => '535','city_province_id' => '6','city_name' => 'آبدانان'),
            array('city_id' => '537','city_province_id' => '7','city_name' => 'بوشهر'),
            array('city_id' => '538','city_province_id' => '7','city_name' => 'گناوه'),
            array('city_id' => '539','city_province_id' => '7','city_name' => 'دیلم'),
            array('city_id' => '540','city_province_id' => '7','city_name' => 'دشتستان'),
            array('city_id' => '541','city_province_id' => '7','city_name' => 'دشتی'),
            array('city_id' => '542','city_province_id' => '7','city_name' => 'تنگستان'),
            array('city_id' => '543','city_province_id' => '7','city_name' => 'کنگان'),
            array('city_id' => '544','city_province_id' => '7','city_name' => 'دیر'),
            array('city_id' => '545','city_province_id' => '7','city_name' => 'جم'),
            array('city_id' => '547','city_province_id' => '8','city_name' => 'پاکدشت'),
            array('city_id' => '548','city_province_id' => '8','city_name' => 'تهران'),
            array('city_id' => '549','city_province_id' => '8','city_name' => 'ری'),
            array('city_id' => '550','city_province_id' => '8','city_name' => 'شمیرانات'),
            array('city_id' => '551','city_province_id' => '8','city_name' => 'اسلامشهر'),
            array('city_id' => '553','city_province_id' => '8','city_name' => 'دماوند'),
            array('city_id' => '554','city_province_id' => '8','city_name' => 'فیروزکوه'),
            array('city_id' => '555','city_province_id' => '8','city_name' => 'رباط کریم'),
            array('city_id' => '557','city_province_id' => '8','city_name' => 'شهریار'),
            array('city_id' => '560','city_province_id' => '8','city_name' => 'ورامین'),
            array('city_id' => '563','city_province_id' => '9','city_name' => 'اردل'),
            array('city_id' => '564','city_province_id' => '9','city_name' => 'فارسان'),
            array('city_id' => '565','city_province_id' => '9','city_name' => 'کوهرنگ'),
            array('city_id' => '568','city_province_id' => '9','city_name' => 'بروجن'),
            array('city_id' => '569','city_province_id' => '9','city_name' => 'شهرکرد'),
            array('city_id' => '572','city_province_id' => '9','city_name' => 'لردگان'),
            array('city_id' => '573','city_province_id' => '10','city_name' => 'بیرجند'),
            array('city_id' => '574','city_province_id' => '10','city_name' => 'درمیان'),
            array('city_id' => '576','city_province_id' => '10','city_name' => 'قائنات'),
            array('city_id' => '578','city_province_id' => '10','city_name' => 'نهبندان'),
            array('city_id' => '579','city_province_id' => '10','city_name' => 'سربیشه'),
            array('city_id' => '580','city_province_id' => '10','city_name' => 'فردوس'),
            array('city_id' => '581','city_province_id' => '10','city_name' => 'سرایان'),
            array('city_id' => '582','city_province_id' => '10','city_name' => 'طبس'),
            array('city_id' => '584','city_province_id' => '11','city_name' => 'تربت جام'),
            array('city_id' => '585','city_province_id' => '11','city_name' => 'تایباد'),
            array('city_id' => '588','city_province_id' => '11','city_name' => 'تربیت حیدریه'),
            array('city_id' => '589','city_province_id' => '11','city_name' => 'مه ولات'),
            array('city_id' => '591','city_province_id' => '11','city_name' => 'چناران'),
            array('city_id' => '593','city_province_id' => '11','city_name' => 'خواف'),
            array('city_id' => '594','city_province_id' => '11','city_name' => 'رشتخوار'),
            array('city_id' => '595','city_province_id' => '11','city_name' => 'درگز'),
            array('city_id' => '596','city_province_id' => '11','city_name' => 'سبزوار'),
            array('city_id' => '601','city_province_id' => '11','city_name' => 'فریمان'),
            array('city_id' => '602','city_province_id' => '11','city_name' => 'سرخس'),
            array('city_id' => '605','city_province_id' => '11','city_name' => 'قوچان'),
            array('city_id' => '606','city_province_id' => '11','city_name' => 'فاروج'),
            array('city_id' => '607','city_province_id' => '11','city_name' => 'کاشمر'),
            array('city_id' => '608','city_province_id' => '11','city_name' => 'خلیل آباد'),
            array('city_id' => '610','city_province_id' => '11','city_name' => 'گناباد'),
            array('city_id' => '612','city_province_id' => '11','city_name' => 'مشهد'),
            array('city_id' => '613','city_province_id' => '11','city_name' => 'کلات'),
            array('city_id' => '614','city_province_id' => '11','city_name' => 'نیشابور'),
            array('city_id' => '616','city_province_id' => '12','city_name' => 'اسفراین'),
            array('city_id' => '617','city_province_id' => '12','city_name' => 'بجنورد'),
            array('city_id' => '618','city_province_id' => '12','city_name' => 'مانه'),
            array('city_id' => '619','city_province_id' => '12','city_name' => 'سملقان'),
            array('city_id' => '620','city_province_id' => '12','city_name' => 'جاجرم'),
            array('city_id' => '624','city_province_id' => '12','city_name' => 'شیروان'),
            array('city_id' => '625','city_province_id' => '13','city_name' => 'آبادن'),
            array('city_id' => '626','city_province_id' => '13','city_name' => 'اندیمشک'),
            array('city_id' => '627','city_province_id' => '13','city_name' => 'اهواز'),
            array('city_id' => '631','city_province_id' => '13','city_name' => 'ایذه'),
            array('city_id' => '633','city_province_id' => '13','city_name' => 'بندر ماهشهر'),
            array('city_id' => '634','city_province_id' => '13','city_name' => 'امیدیه'),
            array('city_id' => '635','city_province_id' => '13','city_name' => 'هندیجان'),
            array('city_id' => '637','city_province_id' => '13','city_name' => 'بهبهان'),
            array('city_id' => '639','city_province_id' => '13','city_name' => 'خرمشهر'),
            array('city_id' => '640','city_province_id' => '13','city_name' => 'دزفول'),
            array('city_id' => '641','city_province_id' => '13','city_name' => 'دشت آزادگان'),
            array('city_id' => '643','city_province_id' => '13','city_name' => 'رامهرمز'),
            array('city_id' => '644','city_province_id' => '13','city_name' => 'رامشیر'),
            array('city_id' => '645','city_province_id' => '13','city_name' => 'شادگان'),
            array('city_id' => '646','city_province_id' => '13','city_name' => 'شوش'),
            array('city_id' => '647','city_province_id' => '13','city_name' => 'شوشتر'),
            array('city_id' => '648','city_province_id' => '13','city_name' => 'گتوند'),
            array('city_id' => '649','city_province_id' => '13','city_name' => 'مسجد سلیمان'),
            array('city_id' => '650','city_province_id' => '13','city_name' => 'لالی'),
            array('city_id' => '653','city_province_id' => '14','city_name' => 'ابهر'),
            array('city_id' => '654','city_province_id' => '14','city_name' => 'خرمدره'),
            array('city_id' => '656','city_province_id' => '14','city_name' => 'خدابنده'),
            array('city_id' => '657','city_province_id' => '14','city_name' => 'زنجان'),
            array('city_id' => '658','city_province_id' => '14','city_name' => 'طارم'),
            array('city_id' => '660','city_province_id' => '14','city_name' => 'ایجرود'),
            array('city_id' => '663','city_province_id' => '15','city_name' => 'دامغان'),
            array('city_id' => '664','city_province_id' => '15','city_name' => 'سمنان'),
            array('city_id' => '665','city_province_id' => '15','city_name' => 'مهدی شهر'),
            array('city_id' => '668','city_province_id' => '15','city_name' => 'شاهرود'),
            array('city_id' => '671','city_province_id' => '15','city_name' => 'گرمسار'),
            array('city_id' => '673','city_province_id' => '16','city_name' => 'ایرانشهر'),
            array('city_id' => '674','city_province_id' => '16','city_name' => 'سرباز'),
            array('city_id' => '675','city_province_id' => '16','city_name' => 'دلگان'),
            array('city_id' => '681','city_province_id' => '16','city_name' => 'چابهار'),
            array('city_id' => '683','city_province_id' => '16','city_name' => 'کنارک'),
            array('city_id' => '685','city_province_id' => '16','city_name' => 'خاش'),
            array('city_id' => '689','city_province_id' => '16','city_name' => 'زابل'),
            array('city_id' => '690','city_province_id' => '16','city_name' => 'زهک'),
            array('city_id' => '694','city_province_id' => '16','city_name' => 'زاهدان'),
            array('city_id' => '695','city_province_id' => '16','city_name' => 'سراوان'),
            array('city_id' => '699','city_province_id' => '17','city_name' => 'آباده'),
            array('city_id' => '700','city_province_id' => '17','city_name' => 'بوانات'),
            array('city_id' => '701','city_province_id' => '17','city_name' => 'خرم بید'),
            array('city_id' => '702','city_province_id' => '17','city_name' => 'نی ریز'),
            array('city_id' => '703','city_province_id' => '17','city_name' => 'استهبان'),
            array('city_id' => '704','city_province_id' => '17','city_name' => 'اقلید'),
            array('city_id' => '705','city_province_id' => '17','city_name' => 'جهرم'),
            array('city_id' => '706','city_province_id' => '17','city_name' => 'داراب'),
            array('city_id' => '707','city_province_id' => '17','city_name' => 'زرین دشت'),
            array('city_id' => '708','city_province_id' => '17','city_name' => 'سپیدان'),
            array('city_id' => '712','city_province_id' => '17','city_name' => 'شیراز'),
            array('city_id' => '713','city_province_id' => '17','city_name' => 'فسا'),
            array('city_id' => '714','city_province_id' => '17','city_name' => 'فیروزآباد'),
            array('city_id' => '715','city_province_id' => '17','city_name' => 'فراشبند'),
            array('city_id' => '716','city_province_id' => '17','city_name' => 'قیر'),
            array('city_id' => '717','city_province_id' => '17','city_name' => 'کارزین'),
            array('city_id' => '718','city_province_id' => '17','city_name' => 'کازرون'),
            array('city_id' => '719','city_province_id' => '17','city_name' => 'لارستان'),
            array('city_id' => '720','city_province_id' => '17','city_name' => 'خنج'),
            array('city_id' => '723','city_province_id' => '17','city_name' => 'مهر'),
            array('city_id' => '724','city_province_id' => '17','city_name' => 'مرودشت'),
            array('city_id' => '725','city_province_id' => '17','city_name' => 'پاسارگاد'),
            array('city_id' => '726','city_province_id' => '17','city_name' => 'ارسنجان'),
            array('city_id' => '727','city_province_id' => '17','city_name' => 'ممسنی'),
            array('city_id' => '729','city_province_id' => '18','city_name' => 'بوئین زهرا'),
            array('city_id' => '731','city_province_id' => '18','city_name' => 'تاکستان'),
            array('city_id' => '732','city_province_id' => '18','city_name' => 'قزوین'),
            array('city_id' => '733','city_province_id' => '18','city_name' => 'آبیک'),
            array('city_id' => '734','city_province_id' => '18','city_name' => 'البرز'),
            array('city_id' => '735','city_province_id' => '19','city_name' => 'قم'),
            array('city_id' => '736','city_province_id' => '20','city_name' => 'بیجار'),
            array('city_id' => '737','city_province_id' => '20','city_name' => 'سقز'),
            array('city_id' => '738','city_province_id' => '20','city_name' => 'بانه'),
            array('city_id' => '739','city_province_id' => '20','city_name' => 'سنندج'),
            array('city_id' => '740','city_province_id' => '20','city_name' => 'دیواندره'),
            array('city_id' => '741','city_province_id' => '20','city_name' => 'کامیاران'),
            array('city_id' => '742','city_province_id' => '20','city_name' => 'قروه'),
            array('city_id' => '744','city_province_id' => '20','city_name' => 'مریوان'),
            array('city_id' => '745','city_province_id' => '20','city_name' => 'سروآباد'),
            array('city_id' => '746','city_province_id' => '21','city_name' => 'بافت'),
            array('city_id' => '749','city_province_id' => '21','city_name' => 'بم'),
            array('city_id' => '753','city_province_id' => '21','city_name' => 'جیرفت'),
            array('city_id' => '754','city_province_id' => '21','city_name' => 'عنبرآباد'),
            array('city_id' => '755','city_province_id' => '21','city_name' => 'رفسنجان'),
            array('city_id' => '757','city_province_id' => '21','city_name' => 'زرند'),
            array('city_id' => '758','city_province_id' => '21','city_name' => 'کوهبنان'),
            array('city_id' => '759','city_province_id' => '21','city_name' => 'سیرجان'),
            array('city_id' => '760','city_province_id' => '21','city_name' => 'بردسیر'),
            array('city_id' => '761','city_province_id' => '21','city_name' => 'شهر بابک'),
            array('city_id' => '762','city_province_id' => '21','city_name' => 'کرمان'),
            array('city_id' => '763','city_province_id' => '21','city_name' => 'راور'),
            array('city_id' => '764','city_province_id' => '21','city_name' => 'کهنوج'),
            array('city_id' => '765','city_province_id' => '21','city_name' => 'منوجان'),
            array('city_id' => '766','city_province_id' => '21','city_name' => 'رودبار جنوب'),
            array('city_id' => '767','city_province_id' => '21','city_name' => 'قلعه گنج'),
            array('city_id' => '769','city_province_id' => '22','city_name' => 'اسلام آباد غرب'),
            array('city_id' => '770','city_province_id' => '22','city_name' => 'دالاهو'),
            array('city_id' => '771','city_province_id' => '22','city_name' => 'پاوه'),
            array('city_id' => '772','city_province_id' => '22','city_name' => 'جوانرود'),
            array('city_id' => '773','city_province_id' => '22','city_name' => 'ثلاث باباجانی'),
            array('city_id' => '774','city_province_id' => '22','city_name' => 'روانسر'),
            array('city_id' => '777','city_province_id' => '22','city_name' => 'سنقر'),
            array('city_id' => '778','city_province_id' => '22','city_name' => 'قصر شیرین'),
            array('city_id' => '779','city_province_id' => '22','city_name' => 'سرپل ذهاب'),
            array('city_id' => '780','city_province_id' => '22','city_name' => 'گیلان غرب'),
            array('city_id' => '781','city_province_id' => '22','city_name' => 'کرمانشاه'),
            array('city_id' => '782','city_province_id' => '22','city_name' => 'کنگاور'),
            array('city_id' => '783','city_province_id' => '22','city_name' => 'صحنه'),
            array('city_id' => '784','city_province_id' => '22','city_name' => 'هرسین'),
            array('city_id' => '785','city_province_id' => '23','city_name' => 'بویراحمد'),
            array('city_id' => '786','city_province_id' => '23','city_name' => 'دنا'),
            array('city_id' => '787','city_province_id' => '23','city_name' => 'کهگیلویه'),
            array('city_id' => '788','city_province_id' => '23','city_name' => 'بهمئی'),
            array('city_id' => '791','city_province_id' => '23','city_name' => 'گچساران'),
            array('city_id' => '793','city_province_id' => '24','city_name' => 'رامیان'),
            array('city_id' => '794','city_province_id' => '24','city_name' => 'آزادشهر'),
            array('city_id' => '795','city_province_id' => '24','city_name' => 'علی آباد'),
            array('city_id' => '796','city_province_id' => '24','city_name' => 'کردکوی'),
            array('city_id' => '797','city_province_id' => '24','city_name' => 'ترکمن'),
            array('city_id' => '798','city_province_id' => '24','city_name' => 'بندر گز'),
            array('city_id' => '800','city_province_id' => '24','city_name' => 'گرگان'),
            array('city_id' => '801','city_province_id' => '24','city_name' => 'آق قلا'),
            array('city_id' => '802','city_province_id' => '24','city_name' => 'گنبد کاووس'),
            array('city_id' => '803','city_province_id' => '24','city_name' => 'مینودشت'),
            array('city_id' => '804','city_province_id' => '24','city_name' => 'کلاله'),
            array('city_id' => '805','city_province_id' => '24','city_name' => 'مراوه تپه'),
            array('city_id' => '807','city_province_id' => '25','city_name' => 'آستارا'),
            array('city_id' => '808','city_province_id' => '25','city_name' => 'آستانه اشرفیه'),
            array('city_id' => '809','city_province_id' => '25','city_name' => 'بندر انزلی'),
            array('city_id' => '810','city_province_id' => '25','city_name' => 'رشت'),
            array('city_id' => '811','city_province_id' => '25','city_name' => 'رودبار'),
            array('city_id' => '812','city_province_id' => '25','city_name' => 'رودسر'),
            array('city_id' => '813','city_province_id' => '25','city_name' => 'املش'),
            array('city_id' => '814','city_province_id' => '25','city_name' => 'صومعه سرا'),
            array('city_id' => '815','city_province_id' => '25','city_name' => 'طوالش'),
            array('city_id' => '816','city_province_id' => '25','city_name' => 'رضوانشهر'),
            array('city_id' => '817','city_province_id' => '25','city_name' => 'ماسال'),
            array('city_id' => '818','city_province_id' => '25','city_name' => 'فومن'),
            array('city_id' => '819','city_province_id' => '25','city_name' => 'شفت'),
            array('city_id' => '820','city_province_id' => '25','city_name' => 'لاهیجان'),
            array('city_id' => '821','city_province_id' => '25','city_name' => 'سیاهکل'),
            array('city_id' => '822','city_province_id' => '25','city_name' => 'لنگرود'),
            array('city_id' => '823','city_province_id' => '26','city_name' => 'الیگودرز'),
            array('city_id' => '824','city_province_id' => '26','city_name' => 'بروجرد'),
            array('city_id' => '825','city_province_id' => '26','city_name' => 'پلدختر'),
            array('city_id' => '826','city_province_id' => '26','city_name' => 'خرم آباد'),
            array('city_id' => '828','city_province_id' => '26','city_name' => 'دلفان'),
            array('city_id' => '829','city_province_id' => '26','city_name' => 'سلسله'),
            array('city_id' => '830','city_province_id' => '26','city_name' => 'دورود'),
            array('city_id' => '831','city_province_id' => '26','city_name' => 'ازنا'),
            array('city_id' => '832','city_province_id' => '26','city_name' => 'کوهدشت'),
            array('city_id' => '834','city_province_id' => '27','city_name' => 'آمل'),
            array('city_id' => '835','city_province_id' => '27','city_name' => 'بابل'),
            array('city_id' => '836','city_province_id' => '27','city_name' => 'بابلسر'),
            array('city_id' => '838','city_province_id' => '27','city_name' => 'بهشهر'),
            array('city_id' => '839','city_province_id' => '27','city_name' => 'نکا'),
            array('city_id' => '840','city_province_id' => '27','city_name' => 'گلوگاه'),
            array('city_id' => '841','city_province_id' => '27','city_name' => 'تنکابن'),
            array('city_id' => '842','city_province_id' => '27','city_name' => 'رامسر'),
            array('city_id' => '844','city_province_id' => '27','city_name' => 'ساری'),
            array('city_id' => '846','city_province_id' => '27','city_name' => 'قائمشهر'),
            array('city_id' => '847','city_province_id' => '27','city_name' => 'سوادکوه'),
            array('city_id' => '848','city_province_id' => '27','city_name' => 'جویبار'),
            array('city_id' => '851','city_province_id' => '27','city_name' => 'نور'),
            array('city_id' => '852','city_province_id' => '27','city_name' => 'محمودآباد'),
            array('city_id' => '853','city_province_id' => '27','city_name' => 'نوشهر'),
            array('city_id' => '854','city_province_id' => '27','city_name' => 'چالوس'),
            array('city_id' => '856','city_province_id' => '28','city_name' => 'اراک'),
            array('city_id' => '857','city_province_id' => '28','city_name' => 'کمیجان'),
            array('city_id' => '859','city_province_id' => '28','city_name' => 'تفرش'),
            array('city_id' => '860','city_province_id' => '28','city_name' => 'آشتیان'),
            array('city_id' => '862','city_province_id' => '28','city_name' => 'خمین'),
            array('city_id' => '863','city_province_id' => '28','city_name' => 'ساوه'),
            array('city_id' => '864','city_province_id' => '28','city_name' => 'زرندیه'),
            array('city_id' => '865','city_province_id' => '28','city_name' => 'شازند'),
            array('city_id' => '866','city_province_id' => '28','city_name' => 'محلات'),
            array('city_id' => '867','city_province_id' => '28','city_name' => 'دلیجان'),
            array('city_id' => '868','city_province_id' => '29','city_name' => 'بندر عباس'),
            array('city_id' => '869','city_province_id' => '29','city_name' => 'قشم'),
            array('city_id' => '870','city_province_id' => '29','city_name' => 'ابوموسی'),
            array('city_id' => '871','city_province_id' => '29','city_name' => 'حاجی آباد'),
            array('city_id' => '872','city_province_id' => '29','city_name' => 'خمیر'),
            array('city_id' => '873','city_province_id' => '29','city_name' => 'بندر لنگه'),
            array('city_id' => '874','city_province_id' => '29','city_name' => 'بستک'),
            array('city_id' => '876','city_province_id' => '29','city_name' => 'میناب'),
            array('city_id' => '877','city_province_id' => '29','city_name' => 'رودان'),
            array('city_id' => '878','city_province_id' => '29','city_name' => 'جاسک'),
            array('city_id' => '881','city_province_id' => '30','city_name' => 'اسدآباد'),
            array('city_id' => '882','city_province_id' => '30','city_name' => 'بهار'),
            array('city_id' => '883','city_province_id' => '30','city_name' => 'کبودرآهنگ'),
            array('city_id' => '884','city_province_id' => '30','city_name' => 'تویسرکان'),
            array('city_id' => '885','city_province_id' => '30','city_name' => 'رزن'),
            array('city_id' => '886','city_province_id' => '30','city_name' => 'ملایر'),
            array('city_id' => '887','city_province_id' => '30','city_name' => 'نهاوند'),
            array('city_id' => '888','city_province_id' => '30','city_name' => 'همدان'),
            array('city_id' => '890','city_province_id' => '31','city_name' => 'اردکان'),
            array('city_id' => '891','city_province_id' => '31','city_name' => 'تفت'),
            array('city_id' => '892','city_province_id' => '31','city_name' => 'میبد'),
            array('city_id' => '893','city_province_id' => '31','city_name' => 'مهریز'),
            array('city_id' => '894','city_province_id' => '31','city_name' => 'بافق'),
            array('city_id' => '895','city_province_id' => '31','city_name' => 'ابرکوه'),
            array('city_id' => '896','city_province_id' => '31','city_name' => 'خاتم'),
            array('city_id' => '898','city_province_id' => '31','city_name' => 'یزد'),
            array('city_id' => '902','city_province_id' => '4','city_name' => 'اصفهان'),
            array('city_id' => '903','city_province_id' => '17','city_name' => 'سروستان'),
            array('city_id' => '904','city_province_id' => '17','city_name' => 'خرامه'),
            array('city_id' => '905','city_province_id' => '17','city_name' => 'کوار'),
            array('city_id' => '906','city_province_id' => '17','city_name' => 'لامرد')
        );
        foreach($data as $value){
            DB::table('city')->insert([
                'city_name' => $value['city_name'],
                'city_province_id' => $value['city_province_id'],
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now()
            ]);
        }

    }
}
