<?php

namespace App\Providers;
use App\Application\Services\Utility\Captcha\CaptchaService;
use App\Application\Services\Utility\DBMessageService;
use App\Domain\Interfaces\Auth\IAuthRepository;
use App\Domain\Interfaces\BossErea\MediaDeputy\IMediaDeputyGovernorRepository;
use App\Domain\Interfaces\BossErea\MeetingDeputy\IMeetingDeputyGovernorRepository;
use App\Domain\Interfaces\BossErea\SessionDeputy\ISessionDeputyGovernorRepository;
use App\Domain\Interfaces\BossErea\TripDeputy\ITripDeputyGovernorRepository;
use App\Domain\Interfaces\Common\Commission\ICommissionRepository;
use App\Domain\Interfaces\Common\Country\ICityRepository;
use App\Domain\Interfaces\Common\Country\IProvinceRepository;
use App\Domain\Interfaces\Common\Election\IElectionLocationRepository;
use App\Domain\Interfaces\Common\Fraction\IFractionRepository;
use App\Domain\Interfaces\Common\GovPeriod\IGovPeriodRepository;
use App\Domain\Interfaces\Common\Ministry\IMinistryRepository;
use App\Domain\Interfaces\Common\PerlemanPeriod\IParlemanPeriodRepository;
use App\Domain\Interfaces\Common\President\IPresidentRepository;
use App\Domain\Interfaces\Common\PresidentCabinet\IPresidentCabinetRepository;
use App\Domain\Interfaces\PersonArea\Enactment\IEnactmentRepository;
use App\Domain\Interfaces\PersonArea\Interpellation\IInterpellationsRepository;
use App\Domain\Interfaces\PersonArea\Meeting\IMeetingRepository;
use App\Domain\Interfaces\PersonArea\Notice\INoticeRepository;
use App\Domain\Interfaces\PersonArea\Person\IPersonRepository;
use App\Domain\Interfaces\PersonArea\PersonResearch\IResearchRepository;
use App\Domain\Interfaces\PersonArea\Projects\IProjectsRepository;
use App\Domain\Interfaces\PersonArea\Question\IQuestionRepository;
use App\Domain\Interfaces\PersonArea\Requests\IRequestsRepository;
use App\Domain\Interfaces\PersonArea\RuleFortyFive\IRuleFortyFiveRepository;
use App\Domain\Interfaces\PersonArea\Rules\IRulesRepository;
use App\Domain\Interfaces\PersonArea\RuleTTF\IRuleTTFRepository;
use App\Domain\Interfaces\PersonArea\Trip\ITripRepository;
use App\Domain\Interfaces\PersonArea\VoteConfident\IVoteConfidenceRepository;
use App\Domain\Interfaces\Utility\Captcha\ICaptchaRepository;
use App\Domain\Interfaces\Utility\IDBMessage;
use App\Domain\Interfaces\Utility\Media\IUploadRepository;
use App\Domain\Interfaces\Utility\Report\IReportRepository;
use App\Infrastructure\Persistence\Repositories\Auth\AuthRepository;
use App\Infrastructure\Persistence\Repositories\BossErea\MediaDeputyGovernor\MediaDeputyGovernorRepository;
use App\Infrastructure\Persistence\Repositories\BossErea\MeetingDeputyGovernor\MeetingDeputyGovernorRepository;
use App\Infrastructure\Persistence\Repositories\BossErea\SessionDeputyGovernor\SessionDeputyGovernorRepository;
use App\Infrastructure\Persistence\Repositories\BossErea\TripDeputyGovernor\TripDeputyGovernorRepository;
use App\Infrastructure\Persistence\Repositories\Common\Commission\CommissionRepository;
use App\Infrastructure\Persistence\Repositories\Common\Country\CityRepository;
use App\Infrastructure\Persistence\Repositories\Common\Country\ProvinceRepository;
use App\Infrastructure\Persistence\Repositories\Common\Election\ElectionLocationRepository;
use App\Infrastructure\Persistence\Repositories\Common\Fraction\FractionRepository;
use App\Infrastructure\Persistence\Repositories\Common\GovPeriod\GovPeriodRepository;
use App\Infrastructure\Persistence\Repositories\Common\Ministry\MinistryRepository;
use App\Infrastructure\Persistence\Repositories\Common\ParlemanPeriod\ParlemanPeriodRepository;
use App\Infrastructure\Persistence\Repositories\Common\President\PresidentRepository;
use App\Infrastructure\Persistence\Repositories\Common\PresidentCabinet\PresidentCabinetRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Enactment\EnactmentRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Interpellation\InterpellationRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Meeting\MeetingRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Notice\NoticeRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Person\PersonRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\PRequest\PersonRequestsRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Projects\ProjectsRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Question\QuestionRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Research\ResearchRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\RuleFortyFive\RuleFortyFiveRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Rules\PersonRulesRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\RuleTTF\RuleTTFRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\Trip\TripRepository;
use App\Infrastructure\Persistence\Repositories\PersonArea\VoteConfidence\VoteConfidenceRepository;
use App\Infrastructure\Persistence\Repositories\Utility\Media\File\UploadRepository;
use App\Infrastructure\Persistence\Repositories\Utility\Report\Report\ReportRepository;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider{

    public function register(): void{
        $this->app->singleton(IAuthRepository::class, AuthRepository::class);
        $this->app->singleton(ICaptchaRepository::class, CaptchaService::class);
        $this->app->singleton(IDBMessage::class, DBMessageService::class);
        $this->app->singleton(ICityRepository::class, CityRepository::class);
        $this->app->singleton(ICommissionRepository::class, CommissionRepository::class);
        $this->app->singleton(IElectionLocationRepository::class, ElectionLocationRepository::class);
        $this->app->singleton(IFractionRepository::class, FractionRepository::class);
        $this->app->singleton(IGovPeriodRepository::class, GovPeriodRepository::class);
        $this->app->singleton(IInterpellationsRepository::class, InterpellationRepository::class);
        $this->app->singleton(IMeetingRepository::class, MeetingRepository::class);
        $this->app->singleton(IMinistryRepository::class, MinistryRepository::class);
        $this->app->singleton(INoticeRepository::class, NoticeRepository::class);
        $this->app->singleton(IParlemanPeriodRepository::class, ParlemanPeriodRepository::class);
        $this->app->singleton(IPersonRepository::class, PersonRepository::class);
        $this->app->singleton(IPresidentRepository::class, PresidentRepository::class);
        $this->app->singleton(IPresidentCabinetRepository::class, PresidentCabinetRepository::class);
        $this->app->singleton(IProvinceRepository::class, ProvinceRepository::class);
        $this->app->singleton(IQuestionRepository::class, QuestionRepository::class);
        $this->app->singleton(IUploadRepository::class, UploadRepository::class);
        $this->app->singleton(IProjectsRepository::class, ProjectsRepository::class);
        $this->app->singleton(IResearchRepository::class, ResearchRepository::class);
        $this->app->singleton(IRequestsRepository::class, PersonRequestsRepository::class);
        $this->app->singleton(IRulesRepository::class, PersonRulesRepository::class);
        $this->app->singleton(IVoteConfidenceRepository::class, VoteConfidenceRepository::class);
        $this->app->singleton(IRuleTTFRepository::class, RuleTTFRepository::class);
        $this->app->singleton(IRuleFortyFiveRepository::class, RuleFortyFiveRepository::class);
        $this->app->singleton(ITripRepository::class, TripRepository::class);
        $this->app->singleton(ITripDeputyGovernorRepository::class, TripDeputyGovernorRepository::class);
        $this->app->singleton(IMediaDeputyGovernorRepository::class, MediaDeputyGovernorRepository::class);
        $this->app->singleton(ISessionDeputyGovernorRepository::class, SessionDeputyGovernorRepository::class);
        $this->app->singleton(IMeetingDeputyGovernorRepository::class, MeetingDeputyGovernorRepository::class);
        $this->app->singleton(IReportRepository::class, ReportRepository::class);
        $this->app->singleton(IEnactmentRepository::class, EnactmentRepository::class);
    }
    public function boot(): void{
        Schema::defaultStringLength(250);
    }
}
